// Generated by CoffeeScript 1.6.3
(function() {
  var modal;

  modal = new ModelView();

  $('#showModal').on('click', function(e) {
    modal.setTitle('Modal Example');
    modal.addCloseButton();
    modal.setContent('<p>Hello World</p>');
    modal.setFooter('Home you enjoyed this stupid example');
    return modal.show();
  });

}).call(this);
